apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
#  namespace: observability
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
#  commonName: grafana.devops.wiki.br
  dnsNames:
  - argocd.devops.wiki.br
